language: ruby
rvm:
  - 2.0.0
before_script:
  - "cd spec/dummy; rake db:migrate; cd ../.."
  - "cd spec/dummy; rake db:test:prepare; cd ../.."
notifications:
  recipients:
    - info@jarijokinen.com
