language: ruby
rvm:
  - 1.9.3
  - 1.9.2
before_script:
  - "cd spec/dummy; rake db:migrate; cd ../.."
  - "cd spec/dummy; rake db:test:prepare; cd ../.."
notifications:
  recipients:
    - info@jarijokinen.com
