language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - ree
before_script:
  - "rake db:test:prepare"
notifications:
  recipients:
    - info@jarijokinen.com
